# 1. Definição do Banco de Dados PostgreSQL
databases:
  - name: payment-api-db
    databaseName: payment_challenge
    user: elias_santos_dev
    plan: free

# 2. Definição do Serviço da Aplicação
services:
  - type: web
    name: payment-api
    runtime: node
    plan: free
    repo: https://github.com/Eliazynho/payment-api
    startCommand: npx prisma migrate deploy && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: payment-api-db
          property: connectionString
