databases:
  - name: payment-api-db
    databaseName: payment_challenge
    user: elias_santos_dev
    plan: free

services:
  - type: web
    name: payment-api
    runtime: node
    plan: free
    repo: https://github.com/Eliazynho/payment-api
    branch: main
    buildCommand: npm install # <-- Apenas 'npm install'. O build acontecerá automaticamente.
    startCommand: npm run render:start # <-- Mantém o script de início
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: payment-api-db
          property: connectionString
